### ISSUE TITLE
Default server port can not be configured !

### ISSUE THREAD

**Issue by liyancode** [joychester/Arowana#2]
I set a new "sinatraport: 7788" in config.yml file, then start server, but the port still 9292. I think it is a bug.

**Comment by joychester** [comment]
It is rack default port for 9292 and you can pass -p <port> as an argument to resolve this problem or you can install thin web server and add Rack::Handler::Thin.run Arowana::App, :Port => 7788 to config.ru to customize your running port, i would like to make no changes currently for this one and leave the free options to the users.
